[package]
name = "admin-csr"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
leptos = { version = "0.8", features = ["csr"] }
shared = { path = "../../shared" }

[[bin]]
name = "admin-csr"
path = "src/main.rs"

[lints]
workspace = true
