[package]
name = "admin-ssr"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
leptos = { version = "0.8", features = ["ssr"] }
shared = { path = "../../shared" }

[lib]
crate-type = ["cdylib", "rlib"]
