// GraphQL codegen — emit a TypedDocumentNode TypeScript file per
// `.graphql` operation under `src/lib/graphql/operations/`.
//
// This is a deliberately minimal alternative to `@graphql-codegen/cli`:
// the project's footprint here is one operation (`analyzeEvent`), and
// pulling the full codegen toolchain for one file would dwarf the
// generated output. We keep the surface area small by:
//
//   1. parsing each operation file against the vendored SDL with
//      `graphql-js` (catches schema drift at codegen time);
//   2. emitting a self-contained TS module that re-parses the
//      operation string at module load and exports it as a
//      TypedDocumentNode<Result, Variables>.
//
// The emitted files are committed to `src/lib/graphql/__generated__/`
// (no .gitignore) so `pnpm tsc --noEmit` / `pnpm biome check` work
// without a pre-step and "go to definition" lands inside this repo.
//
// `pnpm graphql:codegen` rewrites the committed files. `pnpm
// graphql:check` runs the same codegen against a temp directory and
// fails if the committed files would change — CI surfaces drift
// between the `.graphql` source and the committed output.

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildSchema,
  type DocumentNode,
  type OperationDefinitionNode,
  parse,
  validate,
} from "graphql";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const REPO_ROOT = resolve(__dirname, "..");
const SDL_PATH = join(REPO_ROOT, "src/lib/graphql/aimer.schema.graphql");
const OPERATIONS_DIR = join(REPO_ROOT, "src/lib/graphql/operations");
const DEFAULT_OUT_DIR = join(REPO_ROOT, "src/lib/graphql/__generated__");

interface CodegenResult {
  /** Map of absolute output path → file content. */
  files: Map<string, string>;
}

/**
 * Convert a `kebab-case-name.graphql` operation file into a TS module
 * that exports an `AnalyzeEventDocument` (operation-name + "Document")
 * TypedDocumentNode, plus the inferred variable / result types.
 */
function emitOperationModule(opName: string, source: string): string {
  // The variable + result interfaces are intentionally hand-written
  // per operation type rather than generated from the SDL. We only
  // have one operation; once a second arrives the codegen will grow
  // a small SDL-walker. Until then this hard-coded mapping keeps the
  // generated output readable.
  if (opName !== "AnalyzeEvent") {
    throw new Error(
      `codegen: unrecognised operation "${opName}". Add a code path under ` +
        `scripts/graphql-codegen.ts when you check in a new operation file.`,
    );
  }

  // Inline the operation source as a backtick-string literal. We escape
  // backticks and `${` so the runtime parse sees the source verbatim
  // even if a future operation includes a `${...}`-shaped placeholder
  // in a comment.
  const escaped = source
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\${/g, "\\${");

  return `// AUTO-GENERATED by scripts/graphql-codegen.ts — do not edit by hand.
// Re-run \`pnpm graphql:codegen\` after editing the corresponding
// operation file under src/lib/graphql/operations/, then commit both
// the .graphql source and the regenerated output in the same diff.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import { type DocumentNode, parse } from "graphql";

export type AnalyzeEventLanguage = "KOREAN" | "ENGLISH";

export interface AnalyzeEventVariables {
  /** JSON-encoded event payload — redacted by aimer-web before this call. */
  eventData: Record<string, unknown>;
  /** LLM provider name, e.g. "openai". */
  name: string;
  /** LLM model id, e.g. "gpt-4o". */
  model: string;
  /** Output language; matches aimer's GraphQL \`Language\` enum exactly. */
  lang: AnalyzeEventLanguage;
}

export interface AnalysisResultPayload {
  threatScore: number;
  analysis: string;
}

export interface AnalyzeEventResponse {
  analyzeEvent: AnalysisResultPayload;
}

export const ANALYZE_EVENT_SOURCE = \`${escaped}\`;

const document: DocumentNode = parse(ANALYZE_EVENT_SOURCE);

export const AnalyzeEventDocument = document as unknown as TypedDocumentNode<
  AnalyzeEventResponse,
  AnalyzeEventVariables
>;
`;
}

/**
 * Validate every operation under `OPERATIONS_DIR` against the vendored
 * SDL and return the TS file content keyed by output path.
 */
function runCodegen(outDir: string): CodegenResult {
  const sdlSource = readFileSync(SDL_PATH, "utf-8");
  const schema = buildSchema(sdlSource);

  const files = new Map<string, string>();
  const entries = readdirSync(OPERATIONS_DIR, { withFileTypes: true });

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".graphql")) continue;

    const opSource = readFileSync(join(OPERATIONS_DIR, entry.name), "utf-8");

    let document: DocumentNode;
    try {
      document = parse(opSource);
    } catch (err) {
      throw new Error(
        `codegen: failed to parse ${entry.name}: ${(err as Error).message}`,
      );
    }

    const errors = validate(schema, document);
    if (errors.length > 0) {
      throw new Error(
        `codegen: ${entry.name} does not validate against the vendored SDL:\n` +
          errors.map((e) => `  - ${e.message}`).join("\n"),
      );
    }

    // Each operation file ships exactly one named operation in v1.
    // A future fragment-sharing case can relax this — none of the
    // current callers need it.
    const ops = document.definitions.filter(
      (d): d is OperationDefinitionNode => d.kind === "OperationDefinition",
    );
    if (ops.length !== 1) {
      throw new Error(
        `codegen: ${entry.name} must contain exactly one named operation, got ${ops.length}`,
      );
    }
    const opName = ops[0].name?.value;
    if (!opName) {
      throw new Error(`codegen: ${entry.name} operation must be named`);
    }

    const moduleSource = emitOperationModule(opName, opSource);
    const baseName = basename(entry.name, ".graphql");
    files.set(join(outDir, `${baseName}.ts`), moduleSource);
  }

  return { files };
}

function writeFiles(files: Map<string, string>): void {
  for (const [path, content] of files) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, "utf-8");
  }
}

/**
 * `pnpm graphql:check` mode: compare in-memory codegen output against
 * the committed files under `DEFAULT_OUT_DIR`. Exit non-zero on drift
 * so CI surfaces the missing regeneration.
 */
function checkAgainstCommitted(): void {
  const { files } = runCodegen(DEFAULT_OUT_DIR);
  const drift: string[] = [];
  for (const [path, expected] of files) {
    let actual: string;
    try {
      actual = readFileSync(path, "utf-8");
    } catch {
      drift.push(`  - missing: ${path}`);
      continue;
    }
    if (actual !== expected) drift.push(`  - out of sync: ${path}`);
  }
  if (drift.length > 0) {
    console.error(
      "graphql:check failed — committed generated files drift from the " +
        "current `.graphql` operations + vendored SDL.\nRun `pnpm graphql:codegen` " +
        "and commit the result.\n" +
        drift.join("\n"),
    );
    process.exit(1);
  }
  console.log(
    `graphql:check OK (${files.size} operation${files.size === 1 ? "" : "s"})`,
  );
}

function main(): void {
  const mode = process.argv[2] ?? "write";
  if (mode === "check") {
    checkAgainstCommitted();
    return;
  }
  if (mode === "write") {
    const { files } = runCodegen(DEFAULT_OUT_DIR);
    writeFiles(files);
    console.log(
      `graphql:codegen wrote ${files.size} file${files.size === 1 ? "" : "s"}`,
    );
    return;
  }
  console.error(`unknown mode: ${mode} (expected "write" or "check")`);
  process.exit(2);
}

main();
