// AUTO-GENERATED by scripts/graphql-codegen.ts — do not edit by hand.
// Types are DERIVED from schemas/aimer.graphql; an SDL change that
// affects this operation will regenerate the diff below.
// Re-run `pnpm graphql:codegen` after editing the corresponding
// operation file under src/lib/graphql/operations/, then commit both
// the .graphql source and the regenerated output in the same diff.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import { type DocumentNode, parse } from "graphql";

export interface CveLandscapeEntryInput {
  cve: string;
  description: string;
}

export interface AnalyzeEventWithCveVariables {
  event: string;
  eventTime: string;
  name: string;
  model: string;
  lang?: "KOREAN" | "ENGLISH" | null;
  cveLandscape: Array<CveLandscapeEntryInput>;
}

export interface AnalysisResult {
  severityScore: number;
  likelihoodScore: number;
  severityFactors: Array<string>;
  likelihoodFactors: Array<string>;
  ttpTags: Array<string>;
  cveRefs: Array<string>;
  analysis: string;
  promptVersion: string;
  modelActualVersion: string;
}

export interface AnalyzeEventWithCveResponse {
  analyzeEvent: AnalysisResult;
}

export const ANALYZE_EVENT_WITH_CVE_SOURCE = `mutation AnalyzeEventWithCve(
  $event: String!
  $eventTime: DateTime!
  $name: String!
  $model: String!
  $lang: Language
  $cveLandscape: [CveLandscapeEntryInput!]!
) {
  analyzeEvent(
    event: $event
    eventTime: $eventTime
    name: $name
    model: $model
    lang: $lang
    cveLandscape: $cveLandscape
  ) {
    severityScore
    likelihoodScore
    severityFactors
    likelihoodFactors
    ttpTags
    cveRefs
    analysis
    promptVersion
    modelActualVersion
  }
}
`;

const document: DocumentNode = parse(ANALYZE_EVENT_WITH_CVE_SOURCE);

// The cast lives on its own const so the exported Document declaration never
// overflows the formatter's line width for a long operation name (the type
// argument list is always broken across lines, keeping output stable).
const typedDocument = document as unknown as TypedDocumentNode<
  AnalyzeEventWithCveResponse,
  AnalyzeEventWithCveVariables
>;

export const AnalyzeEventWithCveDocument = typedDocument;
