// AUTO-GENERATED by scripts/graphql-codegen.ts — do not edit by hand.
// Types are DERIVED from src/lib/graphql/aimer.schema.graphql; an SDL
// change that affects this operation will regenerate the diff below.
// Re-run `pnpm graphql:codegen` after editing the corresponding
// operation file under src/lib/graphql/operations/, then commit both
// the .graphql source and the regenerated output in the same diff.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import { type DocumentNode, parse } from "graphql";

export interface AnalyzeEventVariables {
  eventData: Record<string, unknown>;
  name: string;
  model: string;
  lang: "KOREAN" | "ENGLISH";
}

export interface AnalysisResult {
  threatScore: number;
  analysis: string;
}

export interface AnalyzeEventResponse {
  analyzeEvent: AnalysisResult;
}

export const ANALYZE_EVENT_SOURCE = `mutation AnalyzeEvent(
  $eventData: JSON!
  $name: String!
  $model: String!
  $lang: Language!
) {
  analyzeEvent(eventData: $eventData, name: $name, model: $model, lang: $lang) {
    threatScore
    analysis
  }
}
`;

const document: DocumentNode = parse(ANALYZE_EVENT_SOURCE);

export const AnalyzeEventDocument = document as unknown as TypedDocumentNode<
  AnalyzeEventResponse,
  AnalyzeEventVariables
>;
