// AUTO-GENERATED by scripts/graphql-codegen.ts — do not edit by hand.
// Types are DERIVED from schemas/aimer.graphql; an SDL change that
// affects this operation will regenerate the diff below.
// Re-run `pnpm graphql:codegen` after editing the corresponding
// operation file under src/lib/graphql/operations/, then commit both
// the .graphql source and the regenerated output in the same diff.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import { type DocumentNode, parse } from "graphql";

export interface AnalyzeStoryVariables {
  members: string;
  name: string;
  model: string;
  lang?: "KOREAN" | "ENGLISH" | null;
}

export interface StoryAnalysisResult {
  severityScore: number;
  likelihoodScore: number;
  severityFactors: Array<string>;
  likelihoodFactors: Array<string>;
  ttpTags: Array<string>;
  analysis: string;
  promptVersion: string;
  modelActualVersion: string;
}

export interface AnalyzeStoryResponse {
  analyzeStory: StoryAnalysisResult;
}

export const ANALYZE_STORY_SOURCE = `mutation AnalyzeStory(
  $members: String!
  $name: String!
  $model: String!
  $lang: Language
) {
  analyzeStory(members: $members, name: $name, model: $model, lang: $lang) {
    severityScore
    likelihoodScore
    severityFactors
    likelihoodFactors
    ttpTags
    analysis
    promptVersion
    modelActualVersion
  }
}
`;

const document: DocumentNode = parse(ANALYZE_STORY_SOURCE);

export const AnalyzeStoryDocument = document as unknown as TypedDocumentNode<
  AnalyzeStoryResponse,
  AnalyzeStoryVariables
>;
