// AUTO-GENERATED by scripts/graphql-codegen.ts — do not edit by hand.
// Types are DERIVED from schemas/aimer.graphql; an SDL change that
// affects this operation will regenerate the diff below.
// Re-run `pnpm graphql:codegen` after editing the corresponding
// operation file under src/lib/graphql/operations/, then commit both
// the .graphql source and the regenerated output in the same diff.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import { type DocumentNode, parse } from "graphql";

export interface StoryMemberInput {
  ordinal: number;
  role: string;
  eventTime: string;
  event: string;
}

export interface StoryMetadataInput {
  storyId: string;
  firstSeenAt: string;
  lastSeenAt: string;
  memberCount: number;
  roleDistribution: Array<StoryRoleCountInput>;
}

export interface EnrichmentFactInput {
  text: string;
}

export interface StoryRoleCountInput {
  role: string;
  count: number;
}

export interface AnalyzeStoryVariables {
  customerId: string;
  storyId: string;
  members: Array<StoryMemberInput>;
  storyMetadata: StoryMetadataInput;
  enrichmentFacts: Array<EnrichmentFactInput>;
  name: string;
  model: string;
  lang?: "KOREAN" | "ENGLISH" | null;
}

export interface StoryAnalysisResult {
  severityScore: number;
  likelihoodScore: number;
  severityFactors: Array<string>;
  likelihoodFactors: Array<string>;
  ttpTags: Array<string>;
  analysis: string;
  promptVersion: string;
  modelActualVersion: string;
}

export interface AnalyzeStoryResponse {
  analyzeStory: StoryAnalysisResult;
}

export const ANALYZE_STORY_SOURCE = `mutation AnalyzeStory(
  $customerId: ID!
  $storyId: ID!
  $members: [StoryMemberInput!]!
  $storyMetadata: StoryMetadataInput!
  $enrichmentFacts: [EnrichmentFactInput!]!
  $name: String!
  $model: String!
  $lang: Language
) {
  analyzeStory(
    customerId: $customerId
    storyId: $storyId
    members: $members
    storyMetadata: $storyMetadata
    enrichmentFacts: $enrichmentFacts
    name: $name
    model: $model
    lang: $lang
  ) {
    severityScore
    likelihoodScore
    severityFactors
    likelihoodFactors
    ttpTags
    analysis
    promptVersion
    modelActualVersion
  }
}
`;

const document: DocumentNode = parse(ANALYZE_STORY_SOURCE);

// The cast lives on its own const so the exported Document declaration never
// overflows the formatter's line width for a long operation name (the type
// argument list is always broken across lines, keeping output stable).
const typedDocument = document as unknown as TypedDocumentNode<
  AnalyzeStoryResponse,
  AnalyzeStoryVariables
>;

export const AnalyzeStoryDocument = typedDocument;
