// AUTO-GENERATED by scripts/graphql-codegen.ts — do not edit by hand.
// Re-run `pnpm graphql:codegen` after editing the corresponding
// operation file under src/lib/graphql/operations/, then commit both
// the .graphql source and the regenerated output in the same diff.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import { type DocumentNode, parse } from "graphql";

export type AnalyzeEventLanguage = "KOREAN" | "ENGLISH";

export interface AnalyzeEventVariables {
  /** JSON-encoded event payload — redacted by aimer-web before this call. */
  eventData: Record<string, unknown>;
  /** LLM provider name, e.g. "openai". */
  name: string;
  /** LLM model id, e.g. "gpt-4o". */
  model: string;
  /** Output language; matches aimer's GraphQL `Language` enum exactly. */
  lang: AnalyzeEventLanguage;
}

export interface AnalysisResultPayload {
  threatScore: number;
  analysis: string;
}

export interface AnalyzeEventResponse {
  analyzeEvent: AnalysisResultPayload;
}

export const ANALYZE_EVENT_SOURCE = `mutation AnalyzeEvent(
  $eventData: JSON!
  $name: String!
  $model: String!
  $lang: Language!
) {
  analyzeEvent(eventData: $eventData, name: $name, model: $model, lang: $lang) {
    threatScore
    analysis
  }
}
`;

const document: DocumentNode = parse(ANALYZE_EVENT_SOURCE);

export const AnalyzeEventDocument = document as unknown as TypedDocumentNode<
  AnalyzeEventResponse,
  AnalyzeEventVariables
>;
