// AUTO-GENERATED by scripts/graphql-codegen.ts — do not edit by hand.
// Types are DERIVED from schemas/aimer.graphql; an SDL change that
// affects this operation will regenerate the diff below.
// Re-run `pnpm graphql:codegen` after editing the corresponding
// operation file under src/lib/graphql/operations/, then commit both
// the .graphql source and the regenerated output in the same diff.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import { type DocumentNode, parse } from "graphql";

export interface PeriodicReportInput {
  storyAnalyses: Array<PeriodicStoryAnalysisInput>;
  eventAnalyses: Array<PeriodicEventAnalysisInput>;
  baselineAggregates: PeriodicBaselineAggregatesInput;
  aggregateTtpTags: Array<string>;
}

export interface PeriodicStoryAnalysisInput {
  storyId: string;
  analysis: string;
  severityScore: number;
  likelihoodScore: number;
  severityFactors: Array<string>;
  likelihoodFactors: Array<string>;
  ttpTags: Array<string>;
  priorityTier: string;
}

export interface PeriodicEventAnalysisInput {
  aiceId: string;
  eventKey: string;
  analysis: string;
  severityScore: number;
  likelihoodScore: number;
  severityFactors: Array<string>;
  likelihoodFactors: Array<string>;
  ttpTags: Array<string>;
  priorityTier: string;
}

export interface PeriodicBaselineAggregatesInput {
  totalCount: number;
  categoryDistribution: Array<PeriodicCategoryCountInput>;
  categoryDeltas: Array<PeriodicCategoryDeltaInput>;
  driftSeverity: number;
  driftLikelihood: number;
}

export interface PeriodicCategoryCountInput {
  category?: string | null;
  count: number;
}

export interface PeriodicCategoryDeltaInput {
  category?: string | null;
  delta: number;
}

export interface PeriodicReportVariables {
  customerId: string;
  period: "LIVE" | "DAILY" | "WEEKLY" | "MONTHLY";
  date: string;
  timezone: string;
  name: string;
  model: string;
  lang?: "KOREAN" | "ENGLISH" | null;
  inputs: PeriodicReportInput;
}

export interface PeriodicSecurityReportResult {
  executiveSummary: string;
  storyHighlights: string;
  baselineDrift: string;
  notableEvents: string;
  recommendations: string;
  promptVersion: string;
  modelActualVersion: string;
}

export interface PeriodicReportResponse {
  generatePeriodicSecurityReport: PeriodicSecurityReportResult;
}

export const PERIODIC_REPORT_SOURCE = `mutation PeriodicReport(
  $customerId: ID!
  $period: PeriodType!
  $date: String!
  $timezone: String!
  $name: String!
  $model: String!
  $lang: Language
  $inputs: PeriodicReportInput!
) {
  generatePeriodicSecurityReport(
    customerId: $customerId
    period: $period
    date: $date
    timezone: $timezone
    name: $name
    model: $model
    lang: $lang
    inputs: $inputs
  ) {
    executiveSummary
    storyHighlights
    baselineDrift
    notableEvents
    recommendations
    promptVersion
    modelActualVersion
  }
}
`;

const document: DocumentNode = parse(PERIODIC_REPORT_SOURCE);

export const PeriodicReportDocument = document as unknown as TypedDocumentNode<
  PeriodicReportResponse,
  PeriodicReportVariables
>;
