// AUTO-GENERATED by scripts/graphql-codegen.ts — do not edit by hand.
// Types are DERIVED from schemas/aimer.graphql; an SDL change that
// affects this operation will regenerate the diff below.
// Re-run `pnpm graphql:codegen` after editing the corresponding
// operation file under src/lib/graphql/operations/, then commit both
// the .graphql source and the regenerated output in the same diff.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import { type DocumentNode, parse } from "graphql";

export interface PeriodicReportInputs {
  storyAnalyses: Array<StoryAnalysisInput>;
  eventAnalyses: Array<EventAnalysisInput>;
  baselineAggregates: BaselineAggregatesInput;
  aggregateTtpTags: Array<string>;
  analyzedEventAggregates?: AnalyzedEventAggregatesInput | null;
}

export interface StoryAnalysisInput {
  storyId: string;
  timeRangeStart: string;
  timeRangeEnd: string;
  sections: string;
  severityScore?: number | null;
  likelihoodScore?: number | null;
  severityFactors: Array<string>;
  likelihoodFactors: Array<string>;
  ttpTags: Array<string>;
}

export interface EventAnalysisInput {
  eventRef: string;
  eventTime: string;
  sections: string;
  severityScore?: number | null;
  likelihoodScore?: number | null;
  severityFactors: Array<string>;
  likelihoodFactors: Array<string>;
  ttpTags: Array<string>;
}

export interface BaselineAggregatesInput {
  windowStart: string;
  windowEnd: string;
  totals: BaselineTotalsInput;
  topTechniques: Array<BaselineCountInput>;
  topSensors: Array<BaselineCountInput>;
}

export interface AnalyzedEventAggregatesInput {
  windowStart: string;
  windowEnd: string;
  analyzedCount: number;
  citedCount: number;
  topTechniques: Array<BaselineCountInput>;
  tierDistribution: Array<BaselineCountInput>;
  uncitedRollup: Array<BaselineCountInput>;
  exemplars: Array<LongTailExemplarInput>;
}

export interface BaselineTotalsInput {
  events: number;
  stories: number;
  hosts: number;
}

export interface BaselineCountInput {
  key: string;
  count: number;
}

export interface LongTailExemplarInput {
  technique: string;
  tier: string;
  count: number;
  factor: string;
}

export interface PeriodicReportVariables {
  customerId: string;
  period: "LIVE" | "DAILY" | "WEEKLY" | "MONTHLY";
  date: string;
  timezone: string;
  name: string;
  model: string;
  lang?: "KOREAN" | "ENGLISH" | null;
  inputs: PeriodicReportInputs;
}

export interface PeriodicSecurityReportResult {
  sections: string;
  promptVersion: string;
  modelActualVersion: string;
}

export interface PeriodicReportResponse {
  generatePeriodicSecurityReport: PeriodicSecurityReportResult;
}

export const PERIODIC_REPORT_SOURCE = `mutation PeriodicReport(
  $customerId: ID!
  $period: Period!
  $date: String!
  $timezone: String!
  $name: String!
  $model: String!
  $lang: Language
  $inputs: PeriodicReportInputs!
) {
  generatePeriodicSecurityReport(
    customerId: $customerId
    period: $period
    date: $date
    timezone: $timezone
    name: $name
    model: $model
    lang: $lang
    inputs: $inputs
  ) {
    sections
    promptVersion
    modelActualVersion
  }
}
`;

const document: DocumentNode = parse(PERIODIC_REPORT_SOURCE);

// The cast lives on its own const so the exported Document declaration never
// overflows the formatter's line width for a long operation name (the type
// argument list is always broken across lines, keeping output stable).
const typedDocument = document as unknown as TypedDocumentNode<
  PeriodicReportResponse,
  PeriodicReportVariables
>;

export const PeriodicReportDocument = typedDocument;
