// AUTO-GENERATED by scripts/graphql-codegen.ts — do not edit by hand.
// Types are DERIVED from schemas/aimer.graphql; an SDL change that
// affects this operation will regenerate the diff below.
// Re-run `pnpm graphql:codegen` after editing the corresponding
// operation file under src/lib/graphql/operations/, then commit both
// the .graphql source and the regenerated output in the same diff.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import { type DocumentNode, parse } from "graphql";

export interface TranslateEventVariables {
  analysis: string;
  severityFactors: Array<string>;
  likelihoodFactors: Array<string>;
  targetLang: "KOREAN" | "ENGLISH";
  name: string;
  model: string;
}

export interface AnalysisNarrativeTranslationResult {
  analysis: string;
  severityFactors: Array<string>;
  likelihoodFactors: Array<string>;
  promptVersion: string;
  modelActualVersion: string;
}

export interface TranslateEventResponse {
  translateAnalysisNarrative: AnalysisNarrativeTranslationResult;
}

export const TRANSLATE_EVENT_SOURCE = `mutation TranslateEvent(
  $analysis: String!
  $severityFactors: [String!]!
  $likelihoodFactors: [String!]!
  $targetLang: Language!
  $name: String!
  $model: String!
) {
  translateAnalysisNarrative(
    analysis: $analysis
    severityFactors: $severityFactors
    likelihoodFactors: $likelihoodFactors
    targetLang: $targetLang
    name: $name
    model: $model
  ) {
    analysis
    severityFactors
    likelihoodFactors
    promptVersion
    modelActualVersion
  }
}
`;

const document: DocumentNode = parse(TRANSLATE_EVENT_SOURCE);

export const TranslateEventDocument = document as unknown as TypedDocumentNode<
  TranslateEventResponse,
  TranslateEventVariables
>;
