// AUTO-GENERATED by scripts/graphql-codegen.ts — do not edit by hand.
// Types are DERIVED from schemas/aimer.graphql; an SDL change that
// affects this operation will regenerate the diff below.
// Re-run `pnpm graphql:codegen` after editing the corresponding
// operation file under src/lib/graphql/operations/, then commit both
// the .graphql source and the regenerated output in the same diff.

import type { TypedDocumentNode } from "@graphql-typed-document-node/core";
import { type DocumentNode, parse } from "graphql";

export interface TranslateReportVariables {
  customerId: string;
  sections: string;
  targetLang: "KOREAN" | "ENGLISH";
  model: string;
  name: string;
}

export interface PeriodicSecurityReportResult {
  sections: string;
  promptVersion: string;
  modelActualVersion: string;
}

export interface TranslateReportResponse {
  translatePeriodicSecurityReport: PeriodicSecurityReportResult;
}

export const TRANSLATE_REPORT_SOURCE = `mutation TranslateReport(
  $customerId: ID!
  $sections: String!
  $targetLang: Language!
  $model: String!
  $name: String!
) {
  translatePeriodicSecurityReport(
    customerId: $customerId
    sections: $sections
    targetLang: $targetLang
    model: $model
    name: $name
  ) {
    sections
    promptVersion
    modelActualVersion
  }
}
`;

const document: DocumentNode = parse(TRANSLATE_REPORT_SOURCE);

// The cast lives on its own const so the exported Document declaration never
// overflows the formatter's line width for a long operation name (the type
// argument list is always broken across lines, keeping output stable).
const typedDocument = document as unknown as TypedDocumentNode<
  TranslateReportResponse,
  TranslateReportVariables
>;

export const TranslateReportDocument = typedDocument;
